"""
app.py - Interactive Streamlit Dashboard for Intelligent Self-Healing SDN Network.

Provides comprehensive visual demonstration of:
- Centralized SDN topology & active forwarding routes
- Scheduled physical link failure injection
- Explicit heartbeat-based failure detection
- Dynamic Dijkstra route recalculation & flow installation
- Before / During / After packet delivery trajectories
- Static Baseline vs Self-Healing comparison
"""

import sys
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

from src.config import SimulationConfig
from src.topology.topology_manager import TopologyManager
from src.simulation.traffic_simulator import TrafficSimulator
from src.analytics.analytics_engine import (
    create_topology_plotly_fig,
    create_time_series_plotly_fig,
)
from experiments.baseline import run_baseline_comparison

# Streamlit Page Setup
st.set_page_config(
    page_title="Self-Healing SDN Simulation",
    page_icon="🌐",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom Styling
st.markdown(
    """
    <style>
    .main-title { font-size: 2.2rem; font-weight: 800; color: #1e3a8a; margin-bottom: 0.2rem; }
    .sub-title { font-size: 1.05rem; color: #4b5563; margin-bottom: 1.5rem; }
    .metric-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px; }
    .badge-pass { background-color: #dcfce7; color: #15803d; font-weight: 600; padding: 4px 8px; border-radius: 4px; }
    .badge-fail { background-color: #fee2e2; color: #b91c1c; font-weight: 600; padding: 4px 8px; border-radius: 4px; }
    </style>
    """,
    unsafe_allow_html=True,
)


def main():
    # Header Banner
    st.markdown("<div class='main-title'>🌐 Intelligent Self-Healing SDN Network</div>", unsafe_allow_html=True)
    st.markdown(
        "<div class='sub-title'>Software-Based SDN Control-Plane Simulation, Explicit Fault Detection & Autonomous Dynamic Recovery</div>",
        unsafe_allow_html=True,
    )

    # Sidebar: Simulation Controls
    st.sidebar.header("⚙️ Simulation Controls")

    routing_mode = st.sidebar.selectbox(
        "Routing Engine Mode",
        options=["self_healing", "static"],
        format_func=lambda x: "🟢 Self-Healing SDN (Dynamic Reroute)" if x == "self_healing" else "🔴 Static Routing (No Recovery)",
        help="Select whether controller dynamically reroutes traffic upon failure or leaves stale paths active.",
    )

    sim_duration = st.sidebar.slider(
        "Simulation Duration (units)",
        min_value=15.0,
        max_value=60.0,
        value=30.0,
        step=5.0,
        help="Total discrete simulation time window.",
    )

    packet_rate = st.sidebar.slider(
        "Traffic Generation Rate (pkts/unit)",
        min_value=1.0,
        max_value=15.0,
        value=5.0,
        step=1.0,
        help="Number of packets generated by H1 per simulation time unit.",
    )

    failure_time = st.sidebar.slider(
        "Failure Injection Time (unit)",
        min_value=5.0,
        max_value=sim_duration - 5.0,
        value=10.0,
        step=1.0,
        help="Timestamp when the selected link is physically cut.",
    )

    heartbeat_interval = st.sidebar.slider(
        "Heartbeat Detection Interval (units)",
        min_value=0.5,
        max_value=3.0,
        value=1.0,
        step=0.5,
        help="Polling interval used by failure detector to observe link status.",
    )

    failed_link_choice = st.sidebar.selectbox(
        "Target Link to Disrupt",
        options=[("S2", "S3"), ("S1", "S2"), ("S4", "S5")],
        format_func=lambda pair: f"Link ({pair[0]} <-> {pair[1]})",
        help="Physical link severed during the failure event.",
    )

    st.sidebar.markdown("---")
    run_btn = st.sidebar.button("🚀 Run Simulation", type="primary", use_container_width=True)
    compare_btn = st.sidebar.button("⚖️ Run Baseline vs Self-Healing Comparison", use_container_width=True)

    # Initialize Session State
    if "sim_result" not in st.session_state:
        # Run a default self-healing simulation initially
        default_cfg = SimulationConfig(
            simulation_duration=sim_duration,
            packet_rate=packet_rate,
            failure_time=failure_time,
            heartbeat_interval=heartbeat_interval,
            failed_link=failed_link_choice,
            routing_mode=routing_mode,
        )
        sim = TrafficSimulator(default_cfg)
        st.session_state["sim_result"] = sim.run()
        st.session_state["show_comparison"] = False

    if run_btn:
        cfg = SimulationConfig(
            simulation_duration=sim_duration,
            packet_rate=packet_rate,
            failure_time=failure_time,
            heartbeat_interval=heartbeat_interval,
            failed_link=failed_link_choice,
            routing_mode=routing_mode,
        )
        sim = TrafficSimulator(cfg)
        st.session_state["sim_result"] = sim.run()
        st.session_state["show_comparison"] = False

    if compare_btn:
        st.session_state["show_comparison"] = True

    # Main Tabs
    tab_sim, tab_baseline, tab_packets, tab_architecture = st.tabs(
        ["📊 Simulation & Topology", "⚖️ Baseline Comparison", "📦 Packet Inspector", "📖 Architecture & Concepts"]
    )

    sim_res = st.session_state["sim_result"]
    metrics = sim_res.summary_metrics

    with tab_sim:
        # Top KPI Metrics Row
        col1, col2, col3, col4, col5 = st.columns(5)
        with col1:
            st.metric("Packets Sent", metrics["packets_sent"])
        with col2:
            st.metric("Packets Delivered", metrics["packets_received"])
        with col3:
            st.metric("Packet Delivery Ratio", f"{metrics['pdr_pct']}%")
        with col4:
            st.metric("Packet Loss", f"{metrics['packet_loss_pct']}%")
        with col5:
            rec_str = f"{metrics['recovery_time']} units" if sim_res.config.routing_mode == "self_healing" else "No Recovery"
            st.metric("Total Recovery Time", rec_str)

        st.markdown("---")

        # Two-Column Layout: Topology Graph vs Event / Path Details
        t_col1, t_col2 = st.columns([3, 2])

        with t_col1:
            st.subheader("Network Topology & Active Forwarding Route")
            active_route_view = st.radio(
                "Route Highlight View:",
                options=["Final Installed Route", "Initial Route", "Both Overlaid"],
                horizontal=True,
            )

            highlight_route = (
                sim_res.final_route if active_route_view == "Final Installed Route" else sim_res.initial_route
            )
            failed_link = sim_res.config.failed_link

            topo_fig = create_topology_plotly_fig(
                topology_manager=TopologyManager(),
                active_route=highlight_route,
                failed_link=failed_link,
                title=f"Topology State: Link {failed_link[0]}-{failed_link[1]} Cut",
            )
            st.plotly_chart(topo_fig, use_container_width=True)

        with t_col2:
            st.subheader("Autonomous Recovery Flow")

            init_path_str = " → ".join(sim_res.initial_route)
            final_path_str = " → ".join(sim_res.final_route)

            st.markdown(f"**1. Initial Forwarding Route (t=0.0):**")
            st.code(init_path_str, language="text")

            st.markdown(f"**2. Disrupted Link at t={sim_res.config.failure_time}:**")
            st.error(f"Link {failed_link[0]} ─X─ {failed_link[1]} physical failure injected.")

            if sim_res.config.routing_mode == "self_healing":
                rec = sim_res.recovery_record
                det_time = rec.get("detection_time", "N/A") if rec else "N/A"
                det_delay = rec.get("detection_delay", "N/A") if rec else "N/A"
                reroute_delay = rec.get("reroute_delay", "N/A") if rec else "N/A"
                tot_rec = rec.get("total_recovery_time", "N/A") if rec else "N/A"

                st.markdown(f"**3. Heartbeat Failure Detection:**")
                st.info(f"Detected at **t = {det_time}** (Detection Delay = {det_delay} units)")

                st.markdown(f"**4. Self-Healing Alternate Route:**")
                st.code(final_path_str, language="text")
                st.success(f"Flow updated (Reroute Delay = {reroute_delay} units | Total Recovery Time = {tot_rec} units)")
            else:
                st.warning("⚠️ Static Mode Active: Controller ignored failure. Stale path retained, all subsequent packets targeting broken link dropped.")

        # Time-Series Trajectory Section
        st.subheader("Traffic Trajectory: Throughput & Loss Dynamics")
        det_timestamp = (
            sim_res.recovery_record.get("detection_time")
            if sim_res.recovery_record and sim_res.config.routing_mode == "self_healing"
            else None
        )
        ts_fig = create_time_series_plotly_fig(
            time_series_df=sim_res.time_series_df,
            failure_time=sim_res.config.failure_time,
            detection_time=det_timestamp,
            title="Delivered vs Dropped Packets Over Simulation Time",
        )
        st.plotly_chart(ts_fig, use_container_width=True)

        # Control Plane Event Log Expander
        with st.expander("📜 SDN Controller Event Log"):
            log_df = pd.DataFrame(sim_res.event_log)
            st.dataframe(log_df, use_container_width=True)

    with tab_baseline:
        st.subheader("⚖️ Empirical Baseline Comparison: Static Routing vs Self-Healing SDN")
        st.markdown(
            """
            This experiment validates the core hypothesis of SDN-driven self-healing:
            - **Static Routing Baseline:** The network cannot adapt without manual intervention; traffic traversing the broken link is dropped continuously.
            - **Self-Healing SDN:** The controller detects heartbeat timeout, dynamically invalidates stale flow rules, recomputes the optimal alternate path via Dijkstra, and installs new forwarding rules.
            """
        )

        with st.spinner("Computing comparative benchmark (Static vs Self-Healing)..."):
            res_stat, res_sh, comp_df = run_baseline_comparison(
                simulation_duration=sim_duration,
                packet_rate=packet_rate,
                failure_time=failure_time,
                heartbeat_interval=heartbeat_interval,
                save_outputs=False,
            )

        b_col1, b_col2 = st.columns([1, 1])
        with b_col1:
            st.markdown("#### Performance Metrics Table")
            st.dataframe(comp_df, use_container_width=True)

        with b_col2:
            st.markdown("#### Graphical Comparison")
            m_s = res_stat.summary_metrics
            m_h = res_sh.summary_metrics

            fig_bar = go.Figure(data=[
                go.Bar(name='Static (No Recovery)', x=['PDR (%)', 'Packet Loss (%)', 'Throughput (kbps)'],
                       y=[m_s['pdr_pct'], m_s['packet_loss_pct'], m_s['throughput_kbps']], marker_color='#ef4444'),
                go.Bar(name='Self-Healing SDN', x=['PDR (%)', 'Packet Loss (%)', 'Throughput (kbps)'],
                       y=[m_h['pdr_pct'], m_h['packet_loss_pct'], m_h['throughput_kbps']], marker_color='#22c55e')
            ])
            fig_bar.update_layout(barmode='group', height=360, margin=dict(l=20, r=20, t=30, b=20))
            st.plotly_chart(fig_bar, use_container_width=True)

    with tab_packets:
        st.subheader("📦 Packet-Level Telemetry Inspector")
        df_packets = sim_res.packets_df

        if not df_packets.empty:
            status_filter = st.multiselect(
                "Filter by Packet Status:",
                options=df_packets["status"].unique(),
                default=df_packets["status"].unique(),
            )
            filtered_df = df_packets[df_packets["status"].isin(status_filter)]
            st.dataframe(filtered_df, use_container_width=True)
            st.download_button(
                "📥 Download Packet Telemetry CSV",
                data=filtered_df.to_csv(index=False),
                file_name="packet_telemetry.csv",
                mime="text/csv",
            )
        else:
            st.info("No packet records available.")

    with tab_architecture:
        st.subheader("📖 System Architecture & Engineering Principles")
        st.markdown(
            """
            ### Technical Positioning
            This platform is an **SDN control-plane software simulation** implemented in Python using discrete-event modeling.
            It models the core SDN paradigm:
            - **Control Plane:** Centralized SDN Controller holding global topology knowledge and executing Dijkstra path computation.
            - **Data Plane:** Packet forwarding along installed paths with link-level delays and physical failure states.
            - **Observability:** Heartbeat monitoring for explicit fault detection with measured detection lag.
            - **Actuation:** Flow table update and dynamic traffic rerouting.

            ### Closed-Loop Self-Healing Cycle
            ```
            Physical Fault (t = 10.0)
                   ↓
            Heartbeat Timeout (t = 11.0, Detection Delay = 1.0)
                   ↓
            Controller Learns of Topology Change
                   ↓
            Old Flow Invalidation: H1-S1-S2-S3-H2
                   ↓
            Dijkstra Shortest Path on Active Subgraph
                   ↓
            Alternate Flow Installed: H1-S1-S4-S5-S3-H2 (t = 11.05)
                   ↓
            Data-Plane Traffic Rerouted & Performance Restored
            ```
            """
        )


if __name__ == "__main__":
    main()
